
package databasemysql;
        
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;//PreparedStatement
        
import com.mysql.jdbc.ResultSetMetaData;// data retrive in database mysql
import java.sql.ResultSet;//resultset fun
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

//import java.sql.Statement;
        
import java.sql.SQLException;//error catch
import javax.swing.JOptionPane;



/**
 *
 * @author HACKER PERSON
 */
public class Registration extends javax.swing.JFrame {

    /**
     **** Creates new form Registration  ****
    **/
    public Registration() {
        initComponents();
    }

    
    
    
    //create database data retrive functio and its data pass to table rows
    private void tabledataview(){
               
            try {
             int c;
                                                      //database name=linda
            String urldb="jdbc:mysql://localhost:3306/linda";
            String usernamedb="root";
            String passworddb="";
            
            //2 create a connection
            Connection conn = (Connection) DriverManager.getConnection(urldb, usernamedb, passworddb);
            System.out.println("CONNECTEDD..!");
           
            String selectquery="SELECT *FROM record";
            PreparedStatement insert =(PreparedStatement) conn.prepareStatement(selectquery);
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            
            c=rss.getColumnCount();// int c to get how much index numbers in the database
            
            DefaultTableModel Df=(DefaultTableModel) jTable1.getModel();
            Df.setRowCount(0);
            while(rs.next()){
                Vector v2=new Vector();
                
                for(int a=1; a<=c; a++){
                    // table wala colum piliwel oni
                    v2.add(rs.getString("id"));
                     v2.add(rs.getString("name"));
                      v2.add(rs.getString("mobile"));
                       v2.add(rs.getString("course"));
                       
                }
                Df.addRow(v2);
            }
             
             
            //last close the connection
            conn.close();
        }
        catch (SQLException ex) {
           System.out.println("Error.. is" + ex.getMessage());
           
           //catch the error type and pass to dialogbox
           String stringerrorvariable=ex.getMessage();
           
           JOptionPane.showMessageDialog(this,stringerrorvariable);
        }
        catch (Exception ex) {
           System.out.println("Error.. is" + ex.getMessage());
           
           //catch the error type and pass to dialogbox
           String stringerrorvariable=ex.getMessage();
           
           JOptionPane.showMessageDialog(this,stringerrorvariable);
        }    
    }
        
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtcourse = new javax.swing.JTextField();
        editebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Source Code Pro Light", 0, 18)); // NOI18N
        jLabel1.setText("Student Registration");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setText("Student Name");

        jLabel3.setText("Mobile");

        jLabel4.setText("Course");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        editebtn.setText("Edit");
        editebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editebtnActionPerformed(evt);
            }
        });

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtname)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtcourse)
                        .addComponent(txtmobile))
                    .addContainerGap())
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(viewbtn)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(addbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editebtn)
                            .addGap(14, 14, 14)
                            .addComponent(deletebtn)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebtn)
                    .addComponent(editebtn)
                    .addComponent(addbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewbtn))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Mobile", "Course"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    //add data to inert database
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
      //variables to pass textfeileed values
      String name=txtname.getText();
      String mobile=txtmobile.getText();
      String course=txtcourse.getText();
      
     //create dbconnection with mysql
        try {
            // PreparedStatement insert;
           // Statement insert;
            
            String urldb="jdbc:mysql://localhost:3306/linda";
            String usernamedb="root";
            String passworddb="";
            
            //2 create a connection
            Connection conn = (Connection) DriverManager.getConnection(urldb, usernamedb, passworddb);
            System.out.println("CONNECTEDD..!");
            
            
            
            String addquery="INSERT INTO record(name,mobile,course) VALUES(?,?,?)";
            PreparedStatement insert =(PreparedStatement) conn.prepareStatement(addquery);
            
            insert.setString(1,name);
            insert.setString(2,mobile);
            insert.setString(3,course);
            //save tge data database table array[][]={0=id,1=name,2=mobile,3=course}
            
            
            //now should execute the query
          //  insert.executeUpdate(); ok vithr use klt wad
          //  JOptionPane.showMessageDialog(this,"ADDED SUCCESSFULL..!");
            
             if(insert.executeUpdate()== 1 ){
             System.out.println("Inserted..!"); 
              JOptionPane.showMessageDialog(this,"ADDED SUCCESSFULL..!");
             }else{
                JOptionPane.showMessageDialog(this,"Error IN Add..!");
            }
            
            
             /*
           String sql="INESRT INTO st_table VALUES(4,'NAME',22)";
           Statement st=conn.createStatement(sql);
           
           if(st.executeUpdate(sql)==1){
             System.out.println("Inserted..!");   
             }
             */
             
            //last close the connection
            conn.close();
            
            
            txtname.setText("");
            txtmobile.setText("");
            txtcourse.setText("");
            
            txtname.requestFocus();
        }
        catch (SQLException ex) {
           System.out.println("Error.. is " + ex.getMessage());
         //catch the error type and pass to dialogbox
           String stringerrorvariable=ex.getMessage();
           JOptionPane.showMessageDialog(this,stringerrorvariable);
        }
        
    }//GEN-LAST:event_addbtnActionPerformed

    
    
    
    
    
    
    
    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        
        
    }//GEN-LAST:event_txtnameActionPerformed

    private void editebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editebtnActionPerformed
       
        
        DefaultTableModel Df=(DefaultTableModel) jTable1.getModel();//table valus get
        int selectedIndex = jTable1.getSelectedRow();//seleted row index number catch
        
        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
              //variables to pass values in textfeild
              String name=txtname.getText();
              String mobile=txtmobile.getText();
              String course=txtcourse.getText();
   
            //create dbconnection with mysql
            String urldb="jdbc:mysql://localhost:3306/linda";
            String usernamedb="root";
            String passworddb="";
            
            //2 create a connection
            Connection conn = (Connection) DriverManager.getConnection(urldb, usernamedb, passworddb);
            System.out.println("CONNECTEDD..!");
                                              //1        //2     //3               //4
            String updatequery="  UPDATE record SET name=? , mobile=?, course=? Where id=?    ";
            PreparedStatement insert =(PreparedStatement) conn.prepareStatement(updatequery);
            
            insert.setString(1,name);
            insert.setString(2,mobile);
            insert.setString(3,course);
            insert.setInt(4,id);
            //save tge data database table array[][]={0=id,1=name,2=mobile,3=course}
            
           //now should execute the query
          //  insert.executeUpdate(); ok vithr use klt wad
          //  JOptionPane.showMessageDialog(this,"UPDATED..!");
            
             if(insert.executeUpdate()== 1 ){
             System.out.println("Inserted..!"); 
              JOptionPane.showMessageDialog(this,"UPDATE SUCCESSFULL..!");
             }else{
                JOptionPane.showMessageDialog(this,"Error IN UPDATE..!");
            }
        
            //last close the connection
            conn.close();
            
            
            txtname.setText("");
            txtmobile.setText("");
            txtcourse.setText("");
            txtname.requestFocus();
            
        }
        catch (SQLException ex) {
           System.out.println("Error.. is " + ex.getMessage());
           
           //catch the error type and pass to dialogbox
           String stringerrorvariable=ex.getMessage();
           
           JOptionPane.showMessageDialog(this,stringerrorvariable);
        }
        
    }//GEN-LAST:event_editebtnActionPerformed

    
    
    
    
    
    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // Table view data in database
        
        //function call
           tabledataview();
    }//GEN-LAST:event_viewbtnActionPerformed

    
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // table row click catch the row data pass to textboxes again view
        DefaultTableModel Df=(DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        txtname.setText(Df.getValueAt(selectedIndex, 1).toString());
        txtmobile.setText(Df.getValueAt(selectedIndex, 2).toString());
        txtcourse.setText(Df.getValueAt(selectedIndex, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    
    
    
    
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       //delet the id row data
        DefaultTableModel Df=(DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();  
        
        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            int dialogResult=JOptionPane.showConfirmDialog(null,"Do You Want DELETE This Row-Record.. ?","Worning",JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                
               //create dbconnection with mysql
            String urldb="jdbc:mysql://localhost:3306/linda";
            String usernamedb="root";
            String passworddb="";
            
            //2 create a connection
            Connection conn = (Connection) DriverManager.getConnection(urldb, usernamedb, passworddb);
            System.out.println("CONNECTEDD..!");
     
            String deletequery="DELETE FROM record  WHERE id=?";
            PreparedStatement insert =(PreparedStatement) conn.prepareStatement(deletequery);
            insert.setInt(1,id); 
            
             if(insert.executeUpdate()== 1 ){
             System.out.println("Deleted..!"); 
              JOptionPane.showMessageDialog(this,"DELETE SUCCESSFULL..!");
             }else{
                JOptionPane.showMessageDialog(this,"Error IN DELETE..!");
            }
            
             
            //last close the connection
            conn.close();
            }
            txtname.setText("");
            txtmobile.setText("");
            txtcourse.setText("");
            txtname.requestFocus();
            
        }
        catch (SQLException ex) {
           System.out.println("Error.. is " + ex.getMessage());
           
           //catch the error type and pass to dialogbox
           String stringerrorvariable=ex.getMessage();
           
           JOptionPane.showMessageDialog(this,stringerrorvariable);
        }
       
    }//GEN-LAST:event_deletebtnActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
